### PR TITLE
Fix issue where UDP connection was made to the wrong destination

### LINKED ISSUE #87: Joining a voice channel does not work whatsoever anymore.
When using Alchemy.Voice.join("guild_id", "channel_id"), the bot visibly joins the voice channel, and you can see the message about it joining the gateway:
11:03:44.907 [debug] Voice Gateway for guild_id connected

However, after about 6 seconds, you can see in iex that the join function returns {:error, "Timed out"} which makes the bot unable to play any audio whatsoever, even if it is connected to the gateway.

### PR DESCRIPTION
**Pull request by dongmaster**
This fixes #87

### CODE REVIEW

File: lib/Voice/gateway.ex [hunk 1]
```diff
@@ -30,7 +30,7 @@ defmodule Alchemy.Voice.Gateway do
 
     def heartbeat do
       now = DateTime.utc_now() |> DateTime.to_unix
-      build_payload(now * 1000, :heartbeat)
+      build_payload(now * 100, :heartbeat)
```
Comment (cronokirby) [inline lib/Voice/gateway.ex]: I'm not sure this is necessary?

Looking at the docs, it just specifies that you need a *nonce*
https://discordapp.com/developers/docs/topics/voice-connections
We don't even need to multiply by anything, come to think of it.

If we want to guarantee uniqueness of the nonce, we could use millisecond granularity instead of the default second in DateTime

File: lib/Voice/gateway.ex [hunk 2]
```diff
@@ -136,6 +141,7 @@ defmodule Alchemy.Voice.Gateway do
   def websocket_terminate(why, _conn_state, state) do
     Logger.debug("Voice Gateway for #{state.guild_id} terminated, "
                  <> "reason: #{inspect why}")
+
```
Comment (cronokirby) [inline lib/Voice/gateway.ex:185]: Is this extra line of whitespace from automatic formatting?

If not, let's just remove it, and run elixirfmt afterwards anyways.

**Review by cronokirby — CHANGES_REQUESTED** [review]
Well, thanks for the PR :)

It seems that the voice API has changed under our nose without anyone raising any issues until now. Your fixes seem to follow the updated API, from what I can tell.

There's just a minor issue with the way we do the initial heartbeat payload that I think was changed unnecessarily. (See the comment there)

File: lib/Voice/gateway.ex (hunk 1 above)
Comment (dongmaster) [reply lib/Voice/gateway.ex]: Ah yeah woops. 

I made this change since I saw that the heartbeat interval wasn't set correctly, so I checked the docs and then looked at the ack/nonce sent from discord and compared it to the one we get from the heartbeat function and saw that the one from the heartbeat function was slightly longer, so I just made an assumption and thought it should be the same length, but that probably isn't necessary.

I can revert that change.

File: lib/Voice/gateway.ex (hunk 2 above)
Comment (dongmaster) [reply lib/Voice/gateway.ex:185]: That was accidentally added since I fixed this issue for my own fork of Alchemy first, so I had to clean up two lines I added there. I'll fix it as well.

**Comment by dongmaster** [comment]
No problemo.

I went through your comments and did what you mentioned.

I reverted the 1000 -> 100 change I did in the heartbeat function and I ran mix format on the gateway.ex file as well.

**Comment by cronokirby** [comment]
Nice job :)
